name: Build and publish Storybook

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build_and_deploy_storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      - run: pnpm install --frozen-lockfile

      - run: |
          pnpm -F ./packages/nhsuk-frontend-react sb:build -o ./out-sb
          touch ./packages/nhsuk-frontend-react/out-sb/.nojekyll

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./packages/nhsuk-frontend-react/out-sb
